#!/usr/bin/env bash
# Configuring Nginx server to have a custom 404 page
# Containing the string Ceci n'est pas une page

apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/^\tserver_name.*/a \\trewrite ^/redirect_me https://www.holbertonschool.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/^\tserver_name.*/a \\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\troot /var/www/html/;\n\tinternal;\n\t}' /etc/nginx/sites-available/default
service nginx restart
